/**
 * Ed25519 wire-format helpers for CONTRACT §1.3/§1.4:
 *   token = base64url(payloadJSON) + "." + base64url(rawSig)
 * The signature covers the EXACT payload bytes, so verification must decode
 * the payload segment to raw bytes and verify those bytes directly — never
 * re-serialize the parsed JSON before verifying (that would hide a canonical-
 * JSON mismatch bug in the implementation).
 *
 * TEST_CURRENT / TEST_PREVIOUS are loaded from fixtures/keys.local.json, which
 * is generated by `node test/fixtures/gen-keys.mjs` (see test/README.md). The
 * generated private key for TEST_CURRENT must be pasted into the server's
 * LICENSE_PRIVATE_KEY (.dev.vars) so the live worker signs with the key these
 * tests know how to verify.
 */

import { readFileSync } from 'node:fs'
import {
  createPublicKey,
  generateKeyPairSync,
  sign as cryptoSign,
  verify as cryptoVerify
} from 'node:crypto'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const FIXTURES_DIR = path.dirname(fileURLToPath(import.meta.url)).replace(/helpers$/, 'fixtures')
const KEYS_PATH = path.join(FIXTURES_DIR, 'keys.local.json')

let fixture
try {
  fixture = JSON.parse(readFileSync(KEYS_PATH, 'utf8'))
} catch (err) {
  throw new Error(
    `Missing ${KEYS_PATH}. Run \`node test/fixtures/gen-keys.mjs\` once before running the ` +
      `suite (see test/README.md). Original error: ${err.message}`
  )
}

// { kid, privatePkcs8Base64, publicRawBase64url }
export const TEST_CURRENT = fixture.current
export const TEST_PREVIOUS = fixture.previous

/** The array a desktop client would bake in: CURRENT then PREVIOUS (§1.4). */
export const DEFAULT_KNOWN_PUBKEYS = [
  { kid: TEST_CURRENT.kid, publicRawBase64url: TEST_CURRENT.publicRawBase64url },
  { kid: TEST_PREVIOUS.kid, publicRawBase64url: TEST_PREVIOUS.publicRawBase64url }
]

export function b64urlEncode(bytes) {
  return Buffer.from(bytes).toString('base64url')
}

export function b64urlDecode(str) {
  return Buffer.from(str, 'base64url')
}

function importRawEd25519PublicKey(rawBytesOrB64url) {
  const raw = typeof rawBytesOrB64url === 'string' ? rawBytesOrB64url : b64urlEncode(rawBytesOrB64url)
  return createPublicKey({ key: { kty: 'OKP', crv: 'Ed25519', x: raw }, format: 'jwk' })
}

/**
 * Verify a `payload.sig` artifact against a known-pubkeys array (mirrors the
 * desktop verifier). Returns the parsed payload on success; throws on any
 * failure (malformed token, unknown kid, bad signature).
 */
export function verifyArtifact(token, knownPubkeys = DEFAULT_KNOWN_PUBKEYS) {
  if (typeof token !== 'string') throw new Error('token is not a string')
  const parts = token.split('.')
  if (parts.length !== 2) throw new Error(`malformed token: expected "payload.sig", got ${parts.length} parts`)
  const [payloadPart, sigPart] = parts
  const payloadBytes = b64urlDecode(payloadPart)
  const sigBytes = b64urlDecode(sigPart)

  let payload
  try {
    payload = JSON.parse(payloadBytes.toString('utf8'))
  } catch (err) {
    throw new Error(`payload segment is not valid JSON: ${err.message}`)
  }

  const entry = knownPubkeys.find((k) => k.kid === payload.kid)
  if (!entry) throw new Error(`unknown kid: ${JSON.stringify(payload.kid)}`)

  const pubKey = importRawEd25519PublicKey(entry.publicRawBase64url)
  // Verify the RECEIVED bytes directly, not a re-stringified copy of `payload`.
  const ok = cryptoVerify(null, payloadBytes, pubKey, sigBytes)
  if (!ok) throw new Error('signature verification failed')

  return payload
}

/** Sign a payload with a raw node:crypto Ed25519 KeyObject, using the same wire format as crypto.ts. */
export function signArtifact(payload, privateKeyObject) {
  const payloadBytes = Buffer.from(JSON.stringify(payload))
  const sig = cryptoSign(null, payloadBytes, privateKeyObject)
  return `${b64urlEncode(payloadBytes)}.${b64urlEncode(sig)}`
}

/** Generate an ephemeral Ed25519 keypair for synthetic (non-server) tokens, e.g. key_rotation. */
export function makeEphemeralKeypair(kid) {
  const { privateKey, publicKey } = generateKeyPairSync('ed25519')
  const spkiDer = publicKey.export({ type: 'spki', format: 'der' })
  const rawPub = spkiDer.subarray(spkiDer.length - 32)
  return { kid, privateKey, publicRawBase64url: b64urlEncode(rawPub) }
}
