/**
 * Kitchen Display + order-status board strings (en / fr / ar).
 *
 * One source for both surfaces: the renderer registers them under the `kds.` i18n namespace
 * (src/renderer/src/pages/kds/kds-i18n.ts) and the LAN pages served to tablets/TVs inline the
 * dictionary of the requested language. Placeholders use the i18next `{{name}}` syntax.
 */

const en = {
  title: 'Kitchen Display',
  expoView: 'All stations (Expo)',
  expo: 'Expo',
  station: 'Station',
  dineIn: 'Dine-in',
  takeout: 'Takeout',
  delivery: 'Delivery',
  table: 'Table {{n}}',
  statusNew: 'NEW',
  statusInProgress: 'COOKING',
  statusReady: 'READY',
  statusBumped: 'SERVED',
  statusCancelled: 'CANCELLED',
  updated: 'UPDATED',
  restored: 'RESTORED',
  recalled: 'RECALLED',
  added: 'ADDED',
  removed: 'REMOVED',
  changed: 'CHANGED',
  wasQty: 'was {{n}}',
  orderNote: 'Note',
  combo: 'COMBO: {{name}}',
  modNo: 'NO',
  modExtra: 'EXTRA',
  modLight: 'LIGHT',
  recall: 'Recall',
  undo: 'Undo',
  bumpedToast: 'Order #{{n}} bumped',
  nothingToRecall: 'Nothing to recall',
  allDay: 'All day',
  noTickets: 'No open tickets',
  offline: 'Offline — reconnecting…',
  live: 'Live',
  sound: 'Sound',
  start: 'Start',
  tapToBump: 'Tap card to bump',
  tapToStart: 'Tap anywhere to start the kitchen screen',
  pinTitle: 'Kitchen screen',
  pinPrompt: 'Enter the kitchen screen PIN',
  pinWrong: 'Wrong PIN',
  pinLocked: 'Too many attempts — wait a moment',
  enter: 'Enter',
  actionFailed: 'Action failed — try again',
  boardTitle: 'Order status',
  preparing: 'Preparing',
  ready: 'Ready',
  boardEmpty: '—',
  settingsTitle: 'Kitchen Display (KDS)',
  settingsSubtitle: 'Screens for the kitchen and a pickup board for customers',
  timers: 'Ticket timers',
  warnMinutes: 'Amber after (minutes)',
  lateMinutes: 'Red after (minutes)',
  alerts: 'New ticket alerts',
  soundSetting: 'Play a sound on new tickets',
  flashSetting: 'Flash the screen on new tickets',
  paperTitle: 'Screen instead of paper',
  paperHint: 'Checked stations stop receiving automatic paper kitchen tickets (manual reprints still work).',
  paperExpo: 'Full ticket / unassigned items (Expo)',
  boardSettings: 'Customer order board',
  boardClear: 'Remove ready numbers after (minutes)',
  pinSetting: 'Kitchen screen PIN (tablets / TVs)',
  pinHint: 'Tablets and TVs on the restaurant Wi-Fi ask for this PIN once.',
  changePin: 'Change PIN',
  pinInvalid: 'PIN must be 4 to 6 digits',
  invalidTimers: 'Red must come after amber (whole minutes)',
  lanTitle: 'Open on a tablet or TV',
  lanKds: 'Kitchen screen link',
  lanBoard: 'Customer board link',
  lanOff: 'The local network server is off. Start it from Settings → Tablet / Ambiance screen.',
  thisPc: 'On this computer',
  displayLabel: 'Screen',
  primaryDisplay: 'main screen',
  openKds: 'Open kitchen screen',
  openBoard: 'Open customer board',
  save: 'Save',
  saved: 'Saved',
  close: 'Close'
}

export type KdsStrings = typeof en

const fr: KdsStrings = {
  title: 'Écran cuisine',
  expoView: 'Tous les postes (Expo)',
  expo: 'Expo',
  station: 'Poste',
  dineIn: 'Sur place',
  takeout: 'À emporter',
  delivery: 'Livraison',
  table: 'Table {{n}}',
  statusNew: 'NOUVEAU',
  statusInProgress: 'EN CUISSON',
  statusReady: 'PRÊT',
  statusBumped: 'SERVI',
  statusCancelled: 'ANNULÉ',
  updated: 'MODIFIÉ',
  restored: 'RÉTABLI',
  recalled: 'RAPPELÉ',
  added: 'AJOUTÉ',
  removed: 'RETIRÉ',
  changed: 'MODIFIÉ',
  wasQty: 'avant {{n}}',
  orderNote: 'Note',
  combo: 'MENU : {{name}}',
  modNo: 'SANS',
  modExtra: 'EXTRA',
  modLight: 'LÉGER',
  recall: 'Rappeler',
  undo: 'Annuler',
  bumpedToast: 'Commande n°{{n}} terminée',
  nothingToRecall: 'Rien à rappeler',
  allDay: 'Total du jour',
  noTickets: 'Aucun ticket en cours',
  offline: 'Hors ligne — reconnexion…',
  live: 'En direct',
  sound: 'Son',
  start: 'Commencer',
  tapToBump: 'Touchez un ticket pour le terminer',
  tapToStart: "Touchez l'écran pour démarrer l'écran cuisine",
  pinTitle: 'Écran cuisine',
  pinPrompt: "Saisissez le code PIN de l'écran cuisine",
  pinWrong: 'Code PIN incorrect',
  pinLocked: 'Trop de tentatives — patientez un instant',
  enter: 'Valider',
  actionFailed: 'Échec — réessayez',
  boardTitle: 'Suivi des commandes',
  preparing: 'En préparation',
  ready: 'Prêtes',
  boardEmpty: '—',
  settingsTitle: 'Écran cuisine (KDS)',
  settingsSubtitle: 'Écrans pour la cuisine et tableau de retrait pour les clients',
  timers: 'Minuteurs des tickets',
  warnMinutes: 'Orange après (minutes)',
  lateMinutes: 'Rouge après (minutes)',
  alerts: 'Alertes nouveaux tickets',
  soundSetting: 'Jouer un son pour chaque nouveau ticket',
  flashSetting: "Faire clignoter l'écran pour chaque nouveau ticket",
  paperTitle: "Écran à la place du papier",
  paperHint: 'Les postes cochés ne reçoivent plus de ticket cuisine papier automatique (la réimpression manuelle reste possible).',
  paperExpo: 'Ticket complet / articles non assignés (Expo)',
  boardSettings: 'Tableau des commandes clients',
  boardClear: 'Retirer les numéros prêts après (minutes)',
  pinSetting: "Code PIN de l'écran cuisine (tablettes / TV)",
  pinHint: 'Les tablettes et TV du Wi-Fi du restaurant demandent ce code une seule fois.',
  changePin: 'Changer le code',
  pinInvalid: 'Le code doit comporter 4 à 6 chiffres',
  invalidTimers: "Le rouge doit venir après l'orange (minutes entières)",
  lanTitle: 'Ouvrir sur une tablette ou une TV',
  lanKds: "Lien de l'écran cuisine",
  lanBoard: 'Lien du tableau clients',
  lanOff: "Le serveur réseau local est arrêté. Démarrez-le depuis Paramètres → Tablette / Écran d'ambiance.",
  thisPc: 'Sur cet ordinateur',
  displayLabel: 'Écran',
  primaryDisplay: 'écran principal',
  openKds: "Ouvrir l'écran cuisine",
  openBoard: 'Ouvrir le tableau clients',
  save: 'Enregistrer',
  saved: 'Enregistré',
  close: 'Fermer'
}

const ar: KdsStrings = {
  title: 'شاشة المطبخ',
  expoView: 'كل المحطات (التجميع)',
  expo: 'التجميع',
  station: 'المحطة',
  dineIn: 'في المطعم',
  takeout: 'سفري',
  delivery: 'توصيل',
  table: 'طاولة {{n}}',
  statusNew: 'جديد',
  statusInProgress: 'قيد الطهي',
  statusReady: 'جاهز',
  statusBumped: 'تم التقديم',
  statusCancelled: 'ملغى',
  updated: 'معدّل',
  restored: 'مُستعاد',
  recalled: 'مُسترجع',
  added: 'مضاف',
  removed: 'محذوف',
  changed: 'معدّل',
  wasQty: 'كان {{n}}',
  orderNote: 'ملاحظة',
  combo: 'وجبة: {{name}}',
  modNo: 'بدون',
  modExtra: 'إضافي',
  modLight: 'خفيف',
  recall: 'استرجاع',
  undo: 'تراجع',
  bumpedToast: 'تم إنهاء الطلب رقم {{n}}',
  nothingToRecall: 'لا شيء للاسترجاع',
  allDay: 'إجمالي المطلوب',
  noTickets: 'لا توجد تذاكر مفتوحة',
  offline: 'غير متصل — جارٍ إعادة الاتصال…',
  live: 'مباشر',
  sound: 'الصوت',
  start: 'بدء',
  tapToBump: 'المس التذكرة لإنهائها',
  tapToStart: 'المس الشاشة لتشغيل شاشة المطبخ',
  pinTitle: 'شاشة المطبخ',
  pinPrompt: 'أدخل الرمز السري لشاشة المطبخ',
  pinWrong: 'رمز خاطئ',
  pinLocked: 'محاولات كثيرة — انتظر قليلاً',
  enter: 'دخول',
  actionFailed: 'فشلت العملية — حاول مجدداً',
  boardTitle: 'حالة الطلبات',
  preparing: 'قيد التحضير',
  ready: 'جاهزة',
  boardEmpty: '—',
  settingsTitle: 'شاشة المطبخ (KDS)',
  settingsSubtitle: 'شاشات للمطبخ ولوحة استلام للزبائن',
  timers: 'مؤقتات التذاكر',
  warnMinutes: 'برتقالي بعد (دقائق)',
  lateMinutes: 'أحمر بعد (دقائق)',
  alerts: 'تنبيهات التذاكر الجديدة',
  soundSetting: 'تشغيل صوت عند كل تذكرة جديدة',
  flashSetting: 'وميض الشاشة عند كل تذكرة جديدة',
  paperTitle: 'الشاشة بدل الورق',
  paperHint: 'المحطات المحددة لن تتلقى تذاكر المطبخ الورقية التلقائية (إعادة الطباعة اليدوية تبقى ممكنة).',
  paperExpo: 'التذكرة الكاملة / العناصر غير المسندة (التجميع)',
  boardSettings: 'لوحة طلبات الزبائن',
  boardClear: 'إزالة الأرقام الجاهزة بعد (دقائق)',
  pinSetting: 'الرمز السري لشاشة المطبخ (الأجهزة اللوحية / التلفاز)',
  pinHint: 'تطلب الأجهزة اللوحية والتلفاز المتصلة بشبكة المطعم هذا الرمز مرة واحدة.',
  changePin: 'تغيير الرمز',
  pinInvalid: 'يجب أن يتكون الرمز من 4 إلى 6 أرقام',
  invalidTimers: 'يجب أن يأتي الأحمر بعد البرتقالي (دقائق كاملة)',
  lanTitle: 'فتح على جهاز لوحي أو تلفاز',
  lanKds: 'رابط شاشة المطبخ',
  lanBoard: 'رابط لوحة الزبائن',
  lanOff: 'خادم الشبكة المحلية متوقف. شغّله من الإعدادات ← الجهاز اللوحي / شاشة الأجواء.',
  thisPc: 'على هذا الحاسوب',
  displayLabel: 'الشاشة',
  primaryDisplay: 'الشاشة الرئيسية',
  openKds: 'فتح شاشة المطبخ',
  openBoard: 'فتح لوحة الزبائن',
  save: 'حفظ',
  saved: 'تم الحفظ',
  close: 'إغلاق'
}

export const KDS_STRINGS: Record<'en' | 'fr' | 'ar', KdsStrings> = { en, fr, ar }

export function kdsStringsFor(lang: string | null | undefined): KdsStrings {
  return lang === 'fr' || lang === 'ar' ? KDS_STRINGS[lang] : KDS_STRINGS.en
}
